### ISSUE TITLE
failed to parse

### ISSUE THREAD

**Issue by mayersgamer** [CS2Plugins/WeaponRestrict#13]
09:56:58 [EROR] (cssharp:ConfigManager) Failed to parse configuration file for WeaponRestrict
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.WeaponLimits.1 | LineNumber: 9 | BytePositionInLine: 10.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 86
09:56:58 [EROR] (cssharp:ConfigManager) Failed to parse configuration file for WeaponRestrict
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.WeaponLimits.1 | LineNumber: 9 | BytePositionInLine: 10.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a number.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 86

**Comment by Whaliin** [comment]
Something is wrong with your config. Since you did not provide it I can not help you.

**Comment by mayersgamer** [comment]
// This configuration was automatically generated by CounterStrikeSharp for plugin 'WeaponRestrict', at 2024/08/02 09:47:17
{
  "MessagePrefix": "{Color.Orange}[WeaponRestrict] ",
  "RestrictMessage": "{Color.LightPurple}{0}{Color.Default} is currently restricted to {Color.LightRed}{1}{Color.Default} per team.",
  "DisabledMessage": "{Color.LightPurple}{0}{Color.Default} is currently {Color.LightRed}disabled{Color.Default}.",
  "WeaponQuotas": {
    "weapon_awp": 0.2
  },
  "WeaponLimits": {
    "1": {
      "weapon_awp": 1,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    },
    "5": {
      "weapon_awp": 2,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    },
    "9": {
      "weapon_awp": 3,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    }
  },
  "DoTeamCheck": true,
  "AllowPickup": false,
  "VIPFlag": "@css/vip",
  "MapConfigs": {
    "awp_lego_2": {
      "WeaponQuotas": {
        "weapon_awp": 0.2
      },
      "WeaponLimits": {
        "weapon_awp": 1
      },
      "awp.*": {}
    }
  },
  "ConfigVersion": 2
}

**Comment by Whaliin** [comment]
I will again refer you to [this guide](https://github.com/CS2Plugins/WeaponRestrict#config) that explains how to configure the plugin. You seem to have misunderstood the configuration options.

**Comment by mayersgamer** [comment]
already checked your guide but i cannot seem to understand it.

See awp.* in the example config. You can use a [regular expression](https://regex101.com/) for the map name. Do note that the pattern is already wrapped in ^ and $ for simplicity.

this part i cannot understand , im not a developer just a basic user .

an example with awp_lego_2 will help a lot 🐸
