### ISSUE TITLE
[ERROR] Failed to load plugin after new 1.4 Release

### ISSUE THREAD

**Issue by csportalsk** [CS2Plugins/WeaponRestrict#19]
```
2024-10-31 17:14:42.614 +01:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/***/game/csgo/addons/counterstrikesharp/plugins/WeaponRestrict/WeaponRestrict.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at WeaponRestrict.WeaponRestrictPlugin.Load(Boolean hotReload) in X:\Main.cs:line 100
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```
Linux
Current API Version: v284 (1.0.284+5c9d38b)
Metamod:Source version 2.0.0-dev+1314
[#11:LOADING]: "WeaponRestrict" (1.4.0) by jon, sapphyrus, FireBird & stefanx111

**Comment by Whaliin** [comment]
Hey please make sure you deleted the old WeaponRestrict.json file in gamedata!

**Comment by csportalsk** [comment]
I haven't WeaponRestrict.json file in gamedata folder. This version doesn't need it. But in this version plugin is still loading.
[#11:LOADING]: "WeaponRestrict" (1.4.0) by jon, sapphyrus, FireBird & stefanx111

**Comment by Whaliin** [comment]
Make sure you updated to the actual current version. Preferably delete (but back up) everything related to the old versions and install fresh then you can copy over the settings manually.

If this still does not help, should be something for the CounterStrikeSharp devs to take a look at

**Comment by csportalsk** [comment]
Version is actual as I type 1.4.0. In commit logs I noticed changes for the config file. With updated config file plugin loaded.

**Comment by Whaliin** [comment]
Assuming issue is resolved since plugin loaded with new config file
