### ISSUE TITLE
not loading 20\11

### ISSUE THREAD

**Issue by mayersgamer** [CS2Plugins/WeaponRestrict#20]
not loading

**Comment by Whaliin** [comment]
Can you provide additional information

**Comment by mayersgamer** [comment]
2024-11-22 06:00:15.112 +00:00 [INFO] (cssharp:PluginContext) Loading plugin WeaponRestrict
2024-11-22 06:00:15.120 +00:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/s1/serverfiles/game/csgo/addons/counterstrikesharp/plugins/WeaponRestrict/WeaponRestrict.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at WeaponRestrict.WeaponRestrictPlugin.Load(Boolean hotReload) in X:\Main.cs:line 100
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by Whaliin** [comment]
CS# devs need to update canacquire signature

**Comment by mayersgamer** [comment]
hey bruh why all plugins work exept yours 

this is the reply of cs# 

"CCSPlayer_ItemServices_CanAcquire": {
"signatures": {
"library": "server",
"windows": "48 8B C4 44 89 40 ? 48 89 50 ? 48 89 48",
"linux": "55 48 89 E5 41 57 41 56 48 8D 45 ? 41 55 41 54 53 48 89 CB"
}
