### ISSUE TITLE
[BUG] Failed to parse configuration file for WeaponRestrict

### ISSUE THREAD

**Issue by crashzk** [CS2Plugins/WeaponRestrict#8]
Log error:
```
2024-03-26 17:33:40.000 -03:00 [EROR] (cssharp:ConfigManager) Failed to parse configuration file for WeaponRestrict
System.Text.Json.JsonException: ',' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 16 | BytePositionInLine: 3.
 ---> System.Text.Json.JsonReaderException: ',' is invalid after a single JSON value. Expected end of data. LineNumber: 16 | BytePositionInLine: 3.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 86
```

Config I'm using:
```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'WeaponRestrict', at 2024/03/26 04:58:03
{
  "MessagePrefix": "[ {DarkRed}WeaponRestrict {Default}] ",
  "RestrictMessage": "{Green}{0} {Default}está atualmente restrito a {1} por time.",
  "DisabledMessage": "{Green}{0} {Default}está atualmente {DarkRed}desativado.",
  "WeaponQuotas": {
    "weapon_deagle": 0
  },
  "WeaponLimits": {
    "weapon_deagle": 0
  },
  "DoTeamCheck": false,
  "AllowPickup": false,
  "VIPFlag": "",
  "MapConfigs": {
    }
  },
  "ConfigVersion": 2
}
```

- CSSharp v202 (1.0.202+696ecad)

**Comment by crashzk** [comment]
I made changes to the configuration:
```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'WeaponRestrict', at 2024/03/26 04:58:03
{
  "MessagePrefix": "[ WeaponRestrict ] ",
  "RestrictMessage": "{0} está atualmente restrito a {1} por time.",
  "DisabledMessage": "{0} está atualmente desativado.",
  "WeaponQuotas": {
  },
  "WeaponLimits": {
    "weapon_deagle": 0
  },
  "DoTeamCheck": false,
  "AllowPickup": false,
  "VIPFlag": "",
  "MapConfigs": {
    }
  },
  "ConfigVersion": 2
}
```

Error logs stopped, but the weapons I configured to be restricted are not.
```
2024-03-26 17:33:43.439 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for de_mirage (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
2024-03-26 17:33:51.421 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for awp_battle (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
2024-03-26 17:45:00.101 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for awp_battle (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
2024-03-26 17:51:07.344 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for awp_battle (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
2024-03-26 17:52:05.033 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for de_mirage (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
2024-03-26 17:52:08.493 -03:00 [INFO] plugin:WeaponRestrict WeaponRestrict: Loaded default config for awp_battle (Limits: [weapon_awp, 1], Quotas: [weapon_awp, 0,2])
```

**Comment by Whaliin** [comment]
You are using the wrong color format. Use `{Color.DarkRed}` and the same format for every other color.

Did the issue with the weapon restriction defaults stop?
